version: "3.7"
services:

  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/

  generator:
    build: generator
    ports:
      - "5000:5000"
    volumes:
      - ./generator/rest_api:/rest_api