version: "3.7"
services:

  jupyter:
    image: jupyter/scipy-notebook
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/

  generator:
    build: 
      context: generator
      cache_from: [gluoncollective/collisions:latest]
    ports:
      - "5000:5000"
    volumes:
      - ./generator/rest_api:/rest_api